### ISSUE TITLE
admin init_product_finder.php, $module_file_for_version_check triggers error

### ISSUE THREAD

**Issue by torvista** [Zen4All-nl/Zen-Cart-Product-Finder#1]
Doing some nit-picking with lat9s Report All Errors.
Got an error about $module_file_for_version_check not existing.

I changed this
`$module_file_for_version_check = ($module_file_for_version_check != '') ? DIR_FS_ADMIN . $module_file_for_version_check : '';`

to this

`$module_file_for_version_check = !empty($module_file_for_version_check) ? DIR_FS_ADMIN . $module_file_for_version_check : '';`

**Comment by Zen4All** [comment]
Thanks, I'll update ASAP.
